### ISSUE TITLE
Don't export ports on the host?

### ISSUE THREAD

**Issue by kajmagnus** [oceanprotocol/docker-images#49]
Hi I think you don't need to expose the container port numbers? the services on the same Docker network can access those ports anyway, right. Exporting them on the host = not good for security?

https://github.com/oceanprotocol/docker-images/blob/develop/docker-compose.yml

```
services:
  mongodb:
    image: mongo:3.6
    ports:
    - "27017:27017"      <—— this isn't needed?
    command: mongod
    networks:
    - backend    <— all other services in this netw, can access the port anyway, right
```
